version: "3"

services:
  redisearch:
    build: "./redisearch"
    ports: 
      - 6379:6379
  
  clickhouse:
    build: "./clickhouse"
    ports:
      - 8123:8123
      - 9000:9000
      - 9009:9009
    
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    tty: true
    
  grpc-redisearch:
    build: "./grpc-redisearch"
    ports: 
      - 8090:8090
    depends_on: ["redisearch"]
    links: 
      - redisearch
  
  grpc-clickhouse:
    build: "./grpc-clickhouse"
    ports: 
      - 8091:8091
    depends_on: ["clickhouse"]
    links: 
      - clickhouse

  website:
    build: "./movie-website"
    ports:
      - 3000:3000
    depends_on: ["grpc-redisearch", "grpc-clickhouse"]