// Code generated by protoc-gen-go. DO NOT EDIT.
// source: redisearchpb/redisearch.proto

package redisearchpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Searcher struct {
	Movie                string   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Searcher) Reset()         { *m = Searcher{} }
func (m *Searcher) String() string { return proto.CompactTextString(m) }
func (*Searcher) ProtoMessage()    {}
func (*Searcher) Descriptor() ([]byte, []int) {
	return fileDescriptor_625b029ceb1a09f0, []int{0}
}

func (m *Searcher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Searcher.Unmarshal(m, b)
}
func (m *Searcher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Searcher.Marshal(b, m, deterministic)
}
func (m *Searcher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Searcher.Merge(m, src)
}
func (m *Searcher) XXX_Size() int {
	return xxx_messageInfo_Searcher.Size(m)
}
func (m *Searcher) XXX_DiscardUnknown() {
	xxx_messageInfo_Searcher.DiscardUnknown(m)
}

var xxx_messageInfo_Searcher proto.InternalMessageInfo

func (m *Searcher) GetMovie() string {
	if m != nil {
		return m.Movie
	}
	return ""
}

type Suggester struct {
	Movie                string   `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Suggester) Reset()         { *m = Suggester{} }
func (m *Suggester) String() string { return proto.CompactTextString(m) }
func (*Suggester) ProtoMessage()    {}
func (*Suggester) Descriptor() ([]byte, []int) {
	return fileDescriptor_625b029ceb1a09f0, []int{1}
}

func (m *Suggester) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Suggester.Unmarshal(m, b)
}
func (m *Suggester) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Suggester.Marshal(b, m, deterministic)
}
func (m *Suggester) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Suggester.Merge(m, src)
}
func (m *Suggester) XXX_Size() int {
	return xxx_messageInfo_Suggester.Size(m)
}
func (m *Suggester) XXX_DiscardUnknown() {
	xxx_messageInfo_Suggester.DiscardUnknown(m)
}

var xxx_messageInfo_Suggester proto.InternalMessageInfo

func (m *Suggester) GetMovie() string {
	if m != nil {
		return m.Movie
	}
	return ""
}

type Request struct {
	Searcher             *Searcher  `protobuf:"bytes,1,opt,name=searcher,proto3" json:"searcher,omitempty"`
	Suggester            *Suggester `protobuf:"bytes,2,opt,name=suggester,proto3" json:"suggester,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_625b029ceb1a09f0, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSearcher() *Searcher {
	if m != nil {
		return m.Searcher
	}
	return nil
}

func (m *Request) GetSuggester() *Suggester {
	if m != nil {
		return m.Suggester
	}
	return nil
}

type SearchResponse struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	MovieId              int64    `protobuf:"varint,2,opt,name=movieId,proto3" json:"movieId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_625b029ceb1a09f0, []int{3}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchResponse) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

type SuggestResponse struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuggestResponse) Reset()         { *m = SuggestResponse{} }
func (m *SuggestResponse) String() string { return proto.CompactTextString(m) }
func (*SuggestResponse) ProtoMessage()    {}
func (*SuggestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_625b029ceb1a09f0, []int{4}
}

func (m *SuggestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuggestResponse.Unmarshal(m, b)
}
func (m *SuggestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuggestResponse.Marshal(b, m, deterministic)
}
func (m *SuggestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuggestResponse.Merge(m, src)
}
func (m *SuggestResponse) XXX_Size() int {
	return xxx_messageInfo_SuggestResponse.Size(m)
}
func (m *SuggestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SuggestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SuggestResponse proto.InternalMessageInfo

func (m *SuggestResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*Searcher)(nil), "redisearch.Searcher")
	proto.RegisterType((*Suggester)(nil), "redisearch.Suggester")
	proto.RegisterType((*Request)(nil), "redisearch.Request")
	proto.RegisterType((*SearchResponse)(nil), "redisearch.SearchResponse")
	proto.RegisterType((*SuggestResponse)(nil), "redisearch.SuggestResponse")
}

func init() { proto.RegisterFile("redisearchpb/redisearch.proto", fileDescriptor_625b029ceb1a09f0) }

var fileDescriptor_625b029ceb1a09f0 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x8d, 0x62, 0xd3, 0x1d, 0xa5, 0xc2, 0x58, 0x61, 0xa9, 0x08, 0x35, 0x17, 0x3d, 0xd5,
	0xd2, 0x9e, 0x45, 0xf1, 0xe6, 0x35, 0x7b, 0xf3, 0x66, 0xdb, 0xa1, 0x06, 0xd4, 0xc4, 0x24, 0xdd,
	0xff, 0xe0, 0xbf, 0x16, 0xb3, 0xc9, 0x6e, 0xc4, 0xd5, 0xdb, 0xbe, 0xcd, 0x9b, 0x6f, 0xde, 0x63,
	0xe0, 0xc2, 0xd2, 0x46, 0x39, 0x7a, 0xb6, 0xeb, 0x17, 0xb3, 0xba, 0xe9, 0xc4, 0xcc, 0x58, 0xed,
	0x35, 0x42, 0xf7, 0x47, 0x4c, 0x61, 0x58, 0x85, 0x2f, 0xb2, 0x38, 0x86, 0xc3, 0x37, 0x5d, 0x2b,
	0x2a, 0xd9, 0x94, 0x5d, 0x17, 0xb2, 0x11, 0xe2, 0x12, 0x8a, 0x6a, 0xb7, 0xdd, 0x92, 0xf3, 0x7f,
	0x5a, 0x0c, 0x70, 0x49, 0x1f, 0x3b, 0x72, 0x1e, 0xe7, 0x30, 0x74, 0x91, 0x17, 0x3c, 0x47, 0x8b,
	0xf1, 0x2c, 0x0b, 0x90, 0x76, 0xc9, 0xd6, 0x85, 0x4b, 0x28, 0x5c, 0xe2, 0x97, 0xfb, 0x61, 0xe4,
	0xec, 0xc7, 0x48, 0x7a, 0x94, 0x9d, 0x4f, 0xdc, 0xc3, 0xa8, 0x41, 0x49, 0x72, 0x46, 0xbf, 0x3b,
	0xfa, 0x4e, 0xe6, 0x95, 0x7f, 0x6d, 0x93, 0x05, 0x81, 0x25, 0xf0, 0x10, 0xf1, 0x71, 0x13, 0xd0,
	0x07, 0x32, 0x49, 0x71, 0x05, 0x27, 0x91, 0xfc, 0x3f, 0x62, 0xf1, 0xc9, 0x80, 0x57, 0x64, 0x6b,
	0xb5, 0x26, 0xbc, 0x85, 0x41, 0xb3, 0x16, 0x4f, 0xf3, 0x88, 0xb1, 0xfc, 0x64, 0xf2, 0xbb, 0x6a,
	0x82, 0x8b, 0xbd, 0x39, 0xc3, 0x3b, 0xe0, 0x71, 0x67, 0xff, 0xfc, 0x79, 0x4f, 0xef, 0x1c, 0xf0,
	0x30, 0x7a, 0x3a, 0xce, 0x4f, 0xbb, 0x1a, 0x84, 0x83, 0x2e, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x9d, 0xf2, 0xba, 0x53, 0xf1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	Search(ctx context.Context, in *Request, opts ...grpc.CallOption) (Service_SearchClient, error)
	Suggest(ctx context.Context, in *Request, opts ...grpc.CallOption) (Service_SuggestClient, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Search(ctx context.Context, in *Request, opts ...grpc.CallOption) (Service_SearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Service_serviceDesc.Streams[0], "/redisearch.Service/Search", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Service_SearchClient interface {
	Recv() (*SearchResponse, error)
	grpc.ClientStream
}

type serviceSearchClient struct {
	grpc.ClientStream
}

func (x *serviceSearchClient) Recv() (*SearchResponse, error) {
	m := new(SearchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceClient) Suggest(ctx context.Context, in *Request, opts ...grpc.CallOption) (Service_SuggestClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Service_serviceDesc.Streams[1], "/redisearch.Service/Suggest", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceSuggestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Service_SuggestClient interface {
	Recv() (*SuggestResponse, error)
	grpc.ClientStream
}

type serviceSuggestClient struct {
	grpc.ClientStream
}

func (x *serviceSuggestClient) Recv() (*SuggestResponse, error) {
	m := new(SuggestResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	Search(*Request, Service_SearchServer) error
	Suggest(*Request, Service_SuggestServer) error
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) Search(req *Request, srv Service_SearchServer) error {
	return status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedServiceServer) Suggest(req *Request, srv Service_SuggestServer) error {
	return status.Errorf(codes.Unimplemented, "method Suggest not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).Search(m, &serviceSearchServer{stream})
}

type Service_SearchServer interface {
	Send(*SearchResponse) error
	grpc.ServerStream
}

type serviceSearchServer struct {
	grpc.ServerStream
}

func (x *serviceSearchServer) Send(m *SearchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Service_Suggest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).Suggest(m, &serviceSuggestServer{stream})
}

type Service_SuggestServer interface {
	Send(*SuggestResponse) error
	grpc.ServerStream
}

type serviceSuggestServer struct {
	grpc.ServerStream
}

func (x *serviceSuggestServer) Send(m *SuggestResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "redisearch.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _Service_Search_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Suggest",
			Handler:       _Service_Suggest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "redisearchpb/redisearch.proto",
}
